BEGIN;
UPDATE clientes SET seg_bolsa = true WHERE lower(email) = 'ruben.diaz.granero@gmail.com' OR lower(trim(nombre || ' ' || coalesce(apellidos, ''))) = 'rubén díaz granero' OR lower(trim(nombre)) = 'rubén díaz granero';
UPDATE clientes SET seg_bolsa = true WHERE lower(email) = 'ruben2005hp@gmail.com' OR lower(trim(nombre || ' ' || coalesce(apellidos, ''))) = 'ruben hernández perez' OR lower(trim(nombre)) = 'ruben hernández perez';
UPDATE clientes SET seg_bolsa = true WHERE lower(email) = 'victorgonzalezgall@gmail.com' OR lower(trim(nombre || ' ' || coalesce(apellidos, ''))) = 'victor gonzalez gallardo' OR lower(trim(nombre)) = 'victor gonzalez gallardo';
UPDATE clientes SET seg_bolsa = true WHERE lower(email) = 'aguileraalex170@gmail.com' OR lower(trim(nombre || ' ' || coalesce(apellidos, ''))) = 'alex aguilera' OR lower(trim(nombre)) = 'alex aguilera';
UPDATE clientes SET seg_bolsa = true WHERE lower(email) = 'noeliaa.lc1@gmail.com' OR lower(trim(nombre || ' ' || coalesce(apellidos, ''))) = 'noelia lópez' OR lower(trim(nombre)) = 'noelia lópez';
UPDATE clientes SET seg_bolsa = true WHERE lower(email) = 'gerardcidrera13@gmail.com' OR lower(trim(nombre || ' ' || coalesce(apellidos, ''))) = 'gerard cidrera gonzalez' OR lower(trim(nombre)) = 'gerard cidrera gonzalez';
UPDATE clientes SET seg_bolsa = true WHERE lower(email) = 'theonlyonetanu@gmail.com' OR lower(trim(nombre || ' ' || coalesce(apellidos, ''))) = 'tarunpreet singh kaur' OR lower(trim(nombre)) = 'tarunpreet singh kaur';
UPDATE clientes SET seg_bolsa = true WHERE lower(email) = 'rayanzn09@gmail.com' OR lower(trim(nombre || ' ' || coalesce(apellidos, ''))) = 'rayan zahrane' OR lower(trim(nombre)) = 'rayan zahrane';
UPDATE clientes SET seg_bolsa = true WHERE lower(email) = 'junqueromartin@gmail.com' OR lower(trim(nombre || ' ' || coalesce(apellidos, ''))) = 'martin junquero ojeda' OR lower(trim(nombre)) = 'martin junquero ojeda';
UPDATE clientes SET seg_bolsa = true WHERE lower(email) = 'juanlupi1@gmail.com' OR lower(trim(nombre || ' ' || coalesce(apellidos, ''))) = 'juan antonio callejas garrido' OR lower(trim(nombre)) = 'juan antonio callejas garrido';
UPDATE clientes SET seg_bolsa = true WHERE lower(email) = 'juanbr405@gmail.com' OR lower(trim(nombre || ' ' || coalesce(apellidos, ''))) = 'juan barrera robles' OR lower(trim(nombre)) = 'juan barrera robles';
UPDATE clientes SET seg_bolsa = true WHERE lower(email) = 'ruldisseny@hotmail.es' OR lower(trim(nombre || ' ' || coalesce(apellidos, ''))) = 'raul romero nicolás' OR lower(trim(nombre)) = 'raul romero nicolás';
UPDATE clientes SET seg_bolsa = true WHERE lower(email) = 'vecbcn@gmail.com' OR lower(trim(nombre || ' ' || coalesce(apellidos, ''))) = 'verónica expósito corral' OR lower(trim(nombre)) = 'verónica expósito corral';
UPDATE clientes SET seg_bolsa = true WHERE lower(email) = 'patrizialv6@gmail.com' OR lower(trim(nombre || ' ' || coalesce(apellidos, ''))) = 'patricia leon' OR lower(trim(nombre)) = 'patricia leon';
UPDATE clientes SET seg_bolsa = true WHERE lower(email) = 'silvipb@gmail.com' OR lower(trim(nombre || ' ' || coalesce(apellidos, ''))) = 'silvia parra baños' OR lower(trim(nombre)) = 'silvia parra baños';
UPDATE clientes SET seg_bolsa = true WHERE lower(email) = 'annigarcia72@gmail.com' OR lower(trim(nombre || ' ' || coalesce(apellidos, ''))) = 'ani garcia lopez' OR lower(trim(nombre)) = 'ani garcia lopez';
UPDATE clientes SET seg_bolsa = true WHERE lower(email) = 'maivlis@gmail.com' OR lower(trim(nombre || ' ' || coalesce(apellidos, ''))) = 'silvia martí gil' OR lower(trim(nombre)) = 'silvia martí gil';
UPDATE clientes SET seg_bolsa = true WHERE lower(email) = 'healtytrix@gmail.com' OR lower(trim(nombre || ' ' || coalesce(apellidos, ''))) = 'beatriz viciana castro' OR lower(trim(nombre)) = 'beatriz viciana castro';
UPDATE clientes SET seg_bolsa = true WHERE lower(email) = 'marimartinsosa@gmail.com' OR lower(trim(nombre || ' ' || coalesce(apellidos, ''))) = 'marian martin sosa' OR lower(trim(nombre)) = 'marian martin sosa';
UPDATE clientes SET seg_bolsa = true WHERE lower(email) = 'dialcri@gmail.com' OR lower(trim(nombre || ' ' || coalesce(apellidos, ''))) = 'cristian álvarez diaz' OR lower(trim(nombre)) = 'cristian álvarez diaz';
UPDATE clientes SET seg_bolsa = true WHERE false OR lower(trim(nombre || ' ' || coalesce(apellidos, ''))) = 'marina galera' OR lower(trim(nombre)) = 'marina galera';
UPDATE clientes SET seg_bolsa = true WHERE false OR lower(trim(nombre || ' ' || coalesce(apellidos, ''))) = 'ana castro' OR lower(trim(nombre)) = 'ana castro';
UPDATE clientes SET seg_bolsa = true WHERE false OR lower(trim(nombre || ' ' || coalesce(apellidos, ''))) = 'elia' OR lower(trim(nombre)) = 'elia';
UPDATE clientes SET seg_bolsa = true WHERE false OR lower(trim(nombre || ' ' || coalesce(apellidos, ''))) = 'raul lerma' OR lower(trim(nombre)) = 'raul lerma';
UPDATE clientes SET seg_bolsa = true WHERE false OR lower(trim(nombre || ' ' || coalesce(apellidos, ''))) = 'isa reyes' OR lower(trim(nombre)) = 'isa reyes';
UPDATE clientes SET seg_bolsa = true WHERE false OR lower(trim(nombre || ' ' || coalesce(apellidos, ''))) = 'laia soni' OR lower(trim(nombre)) = 'laia soni';
UPDATE clientes SET seg_bolsa = true WHERE false OR lower(trim(nombre || ' ' || coalesce(apellidos, ''))) = 'susana (rul)' OR lower(trim(nombre)) = 'susana (rul)';
UPDATE clientes SET seg_bolsa = true WHERE false OR lower(trim(nombre || ' ' || coalesce(apellidos, ''))) = 'david (pol)' OR lower(trim(nombre)) = 'david (pol)';
UPDATE clientes SET seg_bolsa = true WHERE false OR lower(trim(nombre || ' ' || coalesce(apellidos, ''))) = 'carla villalta' OR lower(trim(nombre)) = 'carla villalta';
UPDATE clientes SET seg_bolsa = true WHERE false OR lower(trim(nombre || ' ' || coalesce(apellidos, ''))) = 'ester caro' OR lower(trim(nombre)) = 'ester caro';
UPDATE clientes SET seg_bolsa = true WHERE false OR lower(trim(nombre || ' ' || coalesce(apellidos, ''))) = 'reme' OR lower(trim(nombre)) = 'reme';
UPDATE clientes SET seg_bolsa = true WHERE false OR lower(trim(nombre || ' ' || coalesce(apellidos, ''))) = 'mari angeles' OR lower(trim(nombre)) = 'mari angeles';
UPDATE clientes SET seg_bolsa = true WHERE lower(email) = 'siddhartha.14@hotmail.com' OR lower(trim(nombre || ' ' || coalesce(apellidos, ''))) = 'christian cano fernández' OR lower(trim(nombre)) = 'christian cano fernández';
UPDATE clientes SET seg_bolsa = true WHERE false OR lower(trim(nombre || ' ' || coalesce(apellidos, ''))) = 'may reyes' OR lower(trim(nombre)) = 'may reyes';
UPDATE clientes SET seg_bolsa = true WHERE false OR lower(trim(nombre || ' ' || coalesce(apellidos, ''))) = 'mariona amiga laia' OR lower(trim(nombre)) = 'mariona amiga laia';
UPDATE clientes SET seg_bolsa = true WHERE false OR lower(trim(nombre || ' ' || coalesce(apellidos, ''))) = 'ali tazoui' OR lower(trim(nombre)) = 'ali tazoui';
UPDATE clientes SET seg_bolsa = true WHERE false OR lower(trim(nombre || ' ' || coalesce(apellidos, ''))) = 'carlos pipa' OR lower(trim(nombre)) = 'carlos pipa';
UPDATE clientes SET seg_bolsa = true WHERE false OR lower(trim(nombre || ' ' || coalesce(apellidos, ''))) = 'marco pipa' OR lower(trim(nombre)) = 'marco pipa';
UPDATE clientes SET seg_bolsa = true WHERE false OR lower(trim(nombre || ' ' || coalesce(apellidos, ''))) = 'natalia peiro' OR lower(trim(nombre)) = 'natalia peiro';
UPDATE clientes SET seg_bolsa = true WHERE lower(email) = 'claudiaarrebola@gmail.com' OR lower(trim(nombre || ' ' || coalesce(apellidos, ''))) = 'claudia arrebola roca' OR lower(trim(nombre)) = 'claudia arrebola roca';
UPDATE clientes SET seg_bolsa = true WHERE lower(email) = 'ana.mayor01@gmail.com' OR lower(trim(nombre || ' ' || coalesce(apellidos, ''))) = 'ana mayor lombardo' OR lower(trim(nombre)) = 'ana mayor lombardo';
UPDATE clientes SET seg_bolsa = true WHERE lower(email) = 'cristianarjona25@institutdesales.net' OR lower(trim(nombre || ' ' || coalesce(apellidos, ''))) = 'cristian arjona miranda' OR lower(trim(nombre)) = 'cristian arjona miranda';
UPDATE clientes SET seg_bolsa = true WHERE lower(email) = 'lourdescanovas@hotmail.es' OR lower(trim(nombre || ' ' || coalesce(apellidos, ''))) = 'lourdes cánovas rodríguez' OR lower(trim(nombre)) = 'lourdes cánovas rodríguez';
COMMIT;
SELECT count(*) AS con_bolsa FROM clientes WHERE seg_bolsa;