DELETE FROM pagos_cobros_filas;
BEGIN;
INSERT INTO pagos_cobros_filas (orden, etiqueta, cliente_id) VALUES (10, 'ADISGA', 102);
INSERT INTO pagos_cobros_filas (orden, etiqueta, cliente_id) VALUES (20, 'FISIO', 91);
INSERT INTO pagos_cobros_filas (orden, etiqueta, patron) VALUES (40, 'Grupales', 'grupal|ventas efectivo|ventas tpv|ventas bizum|ventas domiciliado|suscripciones');
INSERT INTO pagos_cobros_filas (orden, etiqueta, patron) VALUES (50, 'PATROCINIO: HSN', 'hsn');
INSERT INTO pagos_cobros_filas (orden, etiqueta, patron) VALUES (60, 'VENTA DE MERCHAN', 'merch');
INSERT INTO pagos_cobros_filas (orden, etiqueta, patron) VALUES (70, 'VENTA DE AGUAS', 'agua');
INSERT INTO pagos_cobros_filas (orden, etiqueta, patron) VALUES (80, 'MULTAS', 'multa');
INSERT INTO pagos_cobros_filas (orden, etiqueta, cliente_id) VALUES (90, 'Martin Junquero', 215);
INSERT INTO pagos_cobros_filas (orden, etiqueta, cliente_id) VALUES (100, 'Vinicio', 10);
INSERT INTO pagos_cobros_filas (orden, etiqueta, cliente_id) VALUES (110, 'WALLAPOP', 11);
INSERT INTO pagos_cobros_filas (orden, etiqueta, cliente_id) VALUES (120, 'Ani', 264);
INSERT INTO pagos_cobros_filas (orden, etiqueta, cliente_id) VALUES (140, 'Viti', 14);
INSERT INTO pagos_cobros_filas (orden, etiqueta, cliente_id) VALUES (160, 'Katherine', 286);
INSERT INTO pagos_cobros_filas (orden, etiqueta, cliente_id) VALUES (170, 'Inés', 17);
INSERT INTO pagos_cobros_filas (orden, etiqueta, cliente_id) VALUES (180, 'Júlia de Marco', 71);
INSERT INTO pagos_cobros_filas (orden, etiqueta, cliente_id) VALUES (190, 'Antonio Lozano', 20);
INSERT INTO pagos_cobros_filas (orden, etiqueta, cliente_id) VALUES (200, 'Sandra Martin Jimenez', 249);
INSERT INTO pagos_cobros_filas (orden, etiqueta, cliente_id) VALUES (210, 'Ramón', 157);
INSERT INTO pagos_cobros_filas (orden, etiqueta, cliente_id) VALUES (220, 'Alejandro Cavanillas', 165);
INSERT INTO pagos_cobros_filas (orden, etiqueta, cliente_id) VALUES (230, 'Julia Bascuñana', 156);
INSERT INTO pagos_cobros_filas (orden, etiqueta, cliente_id) VALUES (240, 'Rubén Hernandez', 26);
INSERT INTO pagos_cobros_filas (orden, etiqueta, cliente_id) VALUES (250, 'Raúl Viladecas', 160);
INSERT INTO pagos_cobros_filas (orden, etiqueta, cliente_id) VALUES (270, 'Rubén Diaz', 131);
INSERT INTO pagos_cobros_filas (orden, etiqueta, cliente_id) VALUES (280, 'Cristian EP', 31);
INSERT INTO pagos_cobros_filas (orden, etiqueta, cliente_id) VALUES (290, 'Iker', 273);
INSERT INTO pagos_cobros_filas (orden, etiqueta, cliente_id) VALUES (300, 'Iker revisiones', 33);
INSERT INTO pagos_cobros_filas (orden, etiqueta, cliente_id) VALUES (310, 'Fernando', 276);
INSERT INTO pagos_cobros_filas (orden, etiqueta, cliente_id) VALUES (320, 'Christian Alcalá', 35);
INSERT INTO pagos_cobros_filas (orden, etiqueta, cliente_id) VALUES (340, 'Bea', 268);
INSERT INTO pagos_cobros_filas (orden, etiqueta, cliente_id) VALUES (360, 'Alex Sanchez', 173);
INSERT INTO pagos_cobros_filas (orden, etiqueta, cliente_id) VALUES (370, 'Adrian Monge', 206);
INSERT INTO pagos_cobros_filas (orden, etiqueta, cliente_id) VALUES (380, 'Victor Valero', 214);
INSERT INTO pagos_cobros_filas (orden, etiqueta, cliente_id) VALUES (390, 'Victor Gallardo', 217);
INSERT INTO pagos_cobros_filas (orden, etiqueta, cliente_id) VALUES (400, 'Irene', 172);
INSERT INTO pagos_cobros_filas (orden, etiqueta, cliente_id) VALUES (410, 'Alex Aguilera', 87);
INSERT INTO pagos_cobros_filas (orden, etiqueta, cliente_id) VALUES (420, 'Pol Recasens', 237);
INSERT INTO pagos_cobros_filas (orden, etiqueta, cliente_id) VALUES (430, 'Tomás Peñalba', 241);
INSERT INTO pagos_cobros_filas (orden, etiqueta, cliente_id) VALUES (440, 'Noelia', 242);
INSERT INTO pagos_cobros_filas (orden, etiqueta, cliente_id) VALUES (450, 'Pau Perez', 243);
INSERT INTO pagos_cobros_filas (orden, etiqueta, cliente_id) VALUES (460, 'Gerard Cidrera', 244);
INSERT INTO pagos_cobros_filas (orden, etiqueta, cliente_id) VALUES (470, 'Tarunpreet', 247);
INSERT INTO pagos_cobros_filas (orden, etiqueta, cliente_id) VALUES (480, 'Rayan', 248);
INSERT INTO pagos_cobros_filas (orden, etiqueta, cliente_id) VALUES (490, 'Martí Munar', 258);
INSERT INTO pagos_cobros_filas (orden, etiqueta, cliente_id) VALUES (500, 'Juan Barrera', 239);
INSERT INTO pagos_cobros_filas (orden, etiqueta, cliente_id) VALUES (520, 'Marian', 269);
INSERT INTO pagos_cobros_filas (orden, etiqueta, cliente_id) VALUES (540, 'Claudia', 280);
INSERT INTO pagos_cobros_filas (orden, etiqueta, cliente_id) VALUES (550, 'Ana Mayor', 84);
INSERT INTO pagos_cobros_filas (orden, etiqueta, cliente_id) VALUES (560, 'Joan Bausa', 292);
INSERT INTO pagos_cobros_filas (orden, etiqueta, cliente_id) VALUES (580, 'Erik Mejías', 299);
INSERT INTO pagos_cobros_filas (orden, etiqueta, cliente_id) VALUES (590, 'Adri Garcia', 305);
COMMIT;
SELECT count(*) AS filas FROM pagos_cobros_filas;